module.exports = {
  purge: {
    enabled: true,
    content: ["./src/**/*.{js,jsx,ts,tsx,vue}"],
  },
  theme: {
    extend: {
      borderRadius: {
        none: "0",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "28px",
        full: "9999px",
      },
      colors: {
        primary: "var(--coffee-primary)",
        onPrimary: "var(--coffee-on-primary)",
        primaryContainer: "var(--coffee-primary-container)",
        onPrimaryContainer: "var(--coffee-on-primary-container)",
        secondary: "var(--coffee-secondary)",
        onSecondary: "var(--coffee-on-secondary)",
        secondaryContainer: "var(--coffee-secondary-container)",
        onSecondaryContainer: "var(--coffee-on-secondary-container)",
        background: "var(--coffee-background)",
        onBackground: "var(--coffee-on-background)",
        surface: "var(--coffee-surface)",
        onSurface: "var(--coffee-on-surface)",
        surfaceVariant: "var(--coffee-surface-variant)",
        onSurfaceVariant: "var(--coffee-on-surface-variant)",
        outline: "var(--coffee-outline)",
        outlineVariant: "var(--coffee-outline-variant)",
        divider: "var(--coffee-outline-variant)",
        "custom-green": "#288F4E",
        skeleton: "rgba(0, 0, 0, 0.1)",
      },
    },
  },
};
